version: 1.0.{build}
image: Visual Studio 2022
environment:
  CODECOV_TOKEN:
    secure: lBnsmGfViFcE5WhRiJFS8VqOFPhh44aD60vLRiVJ0IP3sgdFX2pLIs0f1lX+d3te
  TWINE_USERNAME:
    secure: tr99GUQQ0Ikdt9JA+va64A==
  TWINE_PASSWORD:
    secure: OCiDmNRuUNqKg+waxocmtg3do2CGlzaP6K9H0blU+k9qZu3er7Phlu3UMOMtE2701CHsU5pqZtftNdfe6WlFF7PkN20NqEkgNpnAglSCtrPU3IAOe0iHvI4nAHYe7RTDrm6empkRq6JmapqXtlOPsOr5eqZny67e5qGOIN97O96NxbYx7l7/oumpITyceejxRamH1LK6aq70izbfGaNtk0WD1kEnzM6N9vkFCKdIH7fx4kGiOO0tXrkQTuUFIbUd2HyJasjsSYoAwE3ZEqPc5K29bE91rOzcFnJrQC5H4KA=
  SAFETY_API_KEY:
    secure: oFPmi+6TDrgw/U9XrmvyG2ZkMp8enZbqGgkPxuBZWOJYjdr2iw5nw5ymNJ+GyBMH
install:
- cmd: >-
    C:\Python311\python -m venv .env

    .env\Scripts\activate.bat

    python -m pip install --upgrade pip setuptools

    pip install tox
build: off
test_script:
- cmd: tox
deploy: off
